### ISSUE TITLE
How to calculate and choose the vocab size?

### ISSUE THREAD

**Issue by xdwang0726** [ZNLP/NCLS-Corpora#2]
Hi, in your paper, you mentioned that "In our En2Zh NCLS models, the vocabulary size of source-side English words is 100,000, and that of target-side Chinese characters and words are 18,000, and 50,000 respectively." I am wondering how did  you choose the vocab size and how did you calculate them? Thank you!

**Comment by Zhujunnan** [comment]
The vocabulary size depends on the scale of the dataset. Generally, when you calculate the vocabulary size of the target-side, the following two factors should be considered. 
(1) How many words can the vocabulary cover? This correlates highly with the generation of 'UNK's.
(2) Larger vocabulary means more GPU memory and slower inference speed.
When calculating the size of source-side vocabulary, we mainly take the (1) into account.

**Comment by xdwang0726** [comment]
Thank you for your reply! I am wondering how many GPU did you use in training your models. Thank you!

**Comment by Zhujunnan** [comment]
A single NVIDIA TITAN X (12G GPU memory) would be OK!
