### ISSUE TITLE
Question on train-example.json.json

### ISSUE THREAD

**Issue by nakhunchumpolsathien** [ZNLP/NCLS-Corpora#4]
Hello, 

- I would like to know what `train.source` and `train.target`  are.
- Another question is what is the difference between `source.vocab` and `target.vocab`.   For example, in EN2ZH case, is `source.vocab` the  vocab file from English articles? and  `target.vocab` is the vocab file from Chinese summary?  

```
   "train": [
        "/path/to/train.source",
        "/path/to/train.target"
    ],
        .....
    ],
    "vocab": [
        "/path/to/source.vocab",
        "/path/to/target.vocab"
```

Thank you so much.!

**Comment by Zhujunnan** [comment]
Hello,

(1) Each line of 'train.source' file corresponds to a source document, and the summary of this document is located in the same line of 'train.target' file. You can preprocess the original dataset to get these two files.
(2) Your understanding of the vocabulary is right.

I hope the above answers can be helpful to you.

**Comment by nakhunchumpolsathien** [comment]
Thank you so much for your helpful reply @Zhujunnan . 
Just to confirm if I understand it correctly. So the` train.source` and ` train.target` files will look something like these examples below right ?

**train._source_**
```
这个是 汉语主体 1.
这个是 汉语主体 2.
.....
这个是 汉语主体 N.
```
 **train._target_**
```
This is English summary of Chinese body 1. 
This is English summary of Chinese body 2.
.....
This is English summary of Chinese body N.  
```

Thank you so much!

**Comment by Zhujunnan** [comment]
Yes, you are right.

**Comment by jaydenluke** [comment]
Hi @nakhunchumpolsathien and @Zhujunnan, 

Could you please confirm if I understand these file paths correctly, especially in `beaver-2task` and ` beaver-2task+ `.

Given _EN2ZH_ scenario,
**beaver-2task**/train-example.json
```
{
    "train": [
        "/path/to/train.source",         # English Articles
        "/path/to/train.target.ms",      # English Summaries
        "/path/to/train.target.cls".     # Chinese Summaries (translated from English summaries)
    ],
```


**beaver-2task+**/train-example.json
```
{
    "train": [
        "/path/to/train.MT.source.language1",    # English Articles
        "/path/to/train.MT.target.language2",    # ?
        "/path/to/train.CLS.source.language1",   # ?
        "/path/to/train.CLS.target.language2"    # ?
    ],
```
I am not confidently sure about **beaver-2task+** training json settings. Could you please clear it out a little bit.

Thank you very much,
Cheers!

**Comment by Zhujunnan** [comment]
Hi @jaydenluke,

Your understanding of beaver-2task is quite right. In beaver-2task+, take En2Zh as an example, train.MT.source.language1 and train.MT.target.language2 denote the English sentences and Chinese sentences in machine translation dataset respectively. train.CLS.source.language1 and train.CLS.target.language refer to English articles and Chinese summaries respectively.

I hope the comments above could be helpful to you.

**Comment by keith-nlp** [comment]
Hello @Zhujunnan,
There are many useful answers here. Besides, I still have some additional questions regarding `beaver-2task+/train-example.json`. 

According to your EN2ZH dataset (_train_), there are four major elements of a doc namely \<Article>, \<EN-REF>, \<ZH-REF> and \<Back-Translated-EN-REF>. 

For training `beaver-2task+ (EN2ZH)`, it requests these files:
```
"train": [
        "/path/to/train.MT.source.language1",
        "/path/to/train.MT.target.language2",
        "/path/to/train.CLS.source.language1",   # <Article>
        "/path/to/train.CLS.target.language2"    # <ZH-REF>
    ],
```
Your above answer stated that  "train.MT.source.language1 and train.MT.target.language2 denote the English sentences and Chinese sentences in machine translation dataset respectively.".  My questions is which element in the dataset specifically refers to  `MT.source.language1` and` target.language2` ? 

Thank you very much.

**Comment by Zhujunnan** [comment]
Hi @keith-nlp,

The data we released did not include machine translation datasets. In fact, we don't have permission to release these datasets, because these datasets come from LDC corpus, and you should go to [LDC official website](https://www.ldc.upenn.edu/) to get those.

Best Regards!
