### ISSUE TITLE
在位置嵌入里，对于长度大于5000字的英文新闻是怎么处理的了？

### ISSUE THREAD

**Issue by MollyShuu** [ZNLP/NCLS-Corpora#7]
您好，请问在位置嵌入里，对于长度大于5000字的英文新闻是怎么处理的了？
positional_encoding
def positional_encoding(dim, max_len=5000):

**Comment by Zhujunnan** [comment]
我们在预处理的时候就将长度限制为200了，所以训练的时候不会碰到大于5000字的情况啊

**Comment by MollyShuu** [comment]
> 我们在预处理的时候就将长度限制为200了，所以训练的时候不会碰到大于5000字的情况啊

那请问是怎么预处理的了？直接截断吗，还是？
