### ISSUE TITLE
> 我们在预处理的时候就将长度限制为200了，所以训练的时候不会碰到大于5000字的情况啊

### ISSUE THREAD

**Issue by MollyShuu** [ZNLP/NCLS-Corpora#8]
> 我们在预处理的时候就将长度限制为200了，所以训练的时候不会碰到大于5000字的情况啊

那请问是怎么预处理的了？直接截断吗，还是？(●'◡'●)可以共享一下预处理的代码吗？

_Originally posted by @MollyShuu in https://github.com/ZNLP/NCLS-Corpora/issues/7#issuecomment-783838896_

**Comment by Zhujunnan** [comment]
直接截断就行了，这些在论文里面就有描述的。不好意思，因为前段时间太忙，没顾得上查看消息，抱歉
